application_version: v0.5.0
bin_folder:
loader_installed: false
isupdate: true
game_path: C:\\Program Files\\Guild Wars 2
default_configuration:
    arcdps: false
    gw2radial: false
    d912pxy: false
    arcdps_bhud: false
    arcdps_mechanics: false
version:
    arcdps:
    gw2radial: 
    d912pxy:
    arcdps_bhud:
    arcdps_mechanics:
installed:
    arcdps:
    gw2radial: 
    d912pxy:
    arcdps_bhud:
    arcdps_mechanics:
disabled:
    arcdps: false
    gw2radial: false
    d912pxy: false
    arcdps_bhud: false
    arcdps_mechanics: false